ap_scan=1

network={
ssid="waybeam-01"
psk="waybeam-01"
key_mgmt=WPA-PSK
priority=8
}
network={
ssid="waybeam-02"
psk="waybeam-02"
key_mgmt=WPA-PSK
priority=7
}
network={
ssid="waybeam-03"
psk="waybeam-03"
key_mgmt=WPA-PSK
priority=6
}
network={
ssid="waybeam-04"
psk="waybeam-04"
key_mgmt=WPA-PSK
priority=5
}
network={
ssid="waybeam-05"
psk="waybeam-05"
key_mgmt=WPA-PSK
priority=4
}
network={
ssid="waybeam-06"
psk="waybeam-06"
key_mgmt=WPA-PSK
priority=3
}
network={
ssid="waybeam-07"
psk="waybeam-07"
key_mgmt=WPA-PSK
priority=2
}
network={
ssid="waybeam-08"
psk="waybeam-08"
key_mgmt=WPA-PSK
priority=1
}
network={
ssid="OpenIPC"
psk="12345678"
key_mgmt=WPA-PSK
priority=0
}
network={
ssid="waybeam-01"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-02"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-03"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-04"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-05"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-06"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-07"
key_mgmt=NONE
priority=0
}
network={
ssid="waybeam-08"
key_mgmt=NONE
priority=0
}
